on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  weekly-release:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install

      # Run
      - name: Run script
        env:
          TELEGRAM_DEAL_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_DEAL_BOT_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
          POSTGRES_DEAL_PAGES_WATCHER_CONNECTION_STRING: ${{ secrets.POSTGRES_CONNECTION_STRING }}
        run: PYTHONPATH=$(pwd) poetry run python deal_pages_watcher/main.py